# Generated by Django 6.1 on 2026-08-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
